### PR TITLE
build(dockerfile): added an initial dockerfile

### PR DESCRIPTION
**Pull request by travi**
for greenkeeper-keeper/meta#3

### CODE REVIEW

**Comment by travi** [comment]
@cdaringe this branch has your `Dockerfile` added. i've set up an integration with docker hub. you can find the built image here: https://hub.docker.com/r/greenkeeperkeeper/reference-instance/

i havent worked with docker in about 6 months, so i've grown a bit rusty and my machine doesn't really have the right tools to test things out anymore. would you mind take a look and confirming things are working as you would expect with the image?

**Comment by cdaringe** [comment]
sorry for the delay.  ya, this looks great!  on first publish i'll roll my own instance to pull from the image

**Comment by cdaringe** [comment]
actually, we're missing a `npm run build` step

**Comment by travi** [comment]
since i'm so rusty with docker these days, would that need to be another `RUN` step before the `start` `CMD`?

**Comment by travi** [comment]
nevermind, found your PR: https://github.com/greenkeeper-keeper/reference-instance/pull/48

**Pull request merged**
